[tox]
env_list =
    py{310,311,312,313,314}
minversion = 4.55.0

[testenv]
description = Run tests with pytest
package = wheel
wheel_build_env = .pkg
deps =
    check-manifest
    {py314}: readme_renderer
    flake8
	pytest
	mypy
commands =
    pytest {tty:--color=yes} {posargs}
    uv sync --python {envpython}
    uv run python -m pytest {tty:--color=yes} {posargs} --doctest-modules tests --cov --cov-config=pyproject.toml --cov-report=xml
    mypy
